<?php
	namespace App\Service;
	
	class UserAgentParseService
	{
		public function analyseUserAgent(string $userAgent): bool
		{if($userAgent == null){
				return false;
			}elseif ($this->badUserAgent($userAgent)){
				return false;
			}
			
			return true; // No threats detected
		}
		
	/*
		private function badUserAgent(string $userAgent): bool
		{
			$blockedUserAgentList=[
				"/01h4x.com/i",
				"/360Spider/i",
				"/404checker/i",
				"/404enemy/i",
				"/80legs/i",
				"/ADmantX/i",
				"/AIBOT/i",
				"/ALittle\ Client/i",
				"/ASPSeek/i",
				"/Abonti/i",
				"/Aboundex/i",
				"/Aboundexbot/i",
				"/Acunetix/i",
				"/AdsTxtCrawlerTP/i",
				"/AfD-Verbotsverfahren/i",
				"/AhrefsBot/i",
				"/AiHitBot/i",
				"/Aipbot/i",
				"/Alexibot/i",
				"/AllSubmitter/i",
				"/Alligator/i",
				"/AlphaBot/i",
				"/Anarchie/i",
				"/Anarchy/i",
				"/Anarchy99/i",
				"/Ankit/i",
				"/Anthill/i",
				"/Apexoo/i",
				"/Aspiegel/i",
				"/Asterias/i",
				"/Atomseobot/i",
				"/Attach/i",
				"/AwarioRssBot/i",
				"/AwarioSmartBot/i",
				"/BBBike/i",
				"/BDCbot/i",
				"/BDFetch/i",
				"/BLEXBot/i",
				"/BackDoorBot/i",
				"/BackStreet/i",
				"/BackWeb/i",
				"/Backlink-Ceck/i",
				"/BacklinkCrawler/i",
				"/Badass/i",
				"/Bandit/i",
				"/Barkrowler/i",
				"/BatchFTP/i",
				"/Battleztar\ Bazinga/i",
				"/BetaBot/i",
				"/Bigfoot/i",
				"/Bitacle/i",
				"/BlackWidow/i",
				"/Black\ Hole/i",
				"/Blackboard/i",
				"/Blow/i",
				"/BlowFish/i",
				"/Boardreader/i",
				"/Bolt/i",
				"/BotALot/i",
				"/Brandprotect/i",
				"/Brandwatch/i",
				"/Buck/i",
				"/Buddy/i",
				"/BuiltBotTough/i",
				"/BuiltWith/i",
				"/Bullseye/i",
				"/BunnySlippers/i",
				"/BuzzSumo/i",
				"/Bytespider/i",
				"/CATExplorador/i",
				"/CCBot/i",
				"/CODE87/i",
				"/CSHttp/i",
				"/Calculon/i",
				"/CazoodleBot/i",
				"/Cegbfeieh/i",
				"/CensysInspect/i",
				"/CheTeam/i",
				"/CheeseBot/i",
				"/CherryPicker/i",
				"/ChinaClaw/i",
				"/Chlooe/i",
				"/Citoid/i",
				"/Claritybot/i",
				"/Cliqzbot/i",
				"/Cloud\ mapping/i",
				"/Cocolyzebot/i",
				"/Cogentbot/i",
				"/Collector/i",
				"/Copier/i",
				"/CopyRightCheck/i",
				"/Copyscape/i",
				"/Cosmos/i",
				"/Craftbot/i",
				"/Crawling\ at\ Home\ Project/i",
				"/CrazyWebCrawler/i",
				"/Crescent/i",
				"/CrunchBot/i",
				"/Curious/i",
				"/Custo/i",
				"/CyotekWebCopy/i",
				"/DBLBot/i",
				"/DIIbot/i",
				"/DSearch/i",
				"/DTS\ Agent/i",
				"/DataCha0s/i",
				"/DatabaseDriverMysqli/i",
				"/Demon/i",
				"/Deusu/i",
				"/Devil/i",
				"/Digincore/i",
				"/DigitalPebble/i",
				"/Dirbuster/i",
				"/Disco/i",
				"/Discobot/i",
				"/Discoverybot/i",
				"/Dispatch/i",
				"/DittoSpyder/i",
				"/DnBCrawler-Analytics/i",
				"/DnyzBot/i",
				"/DomCopBot/i",
				"/DomainAppender/i",
				"/DomainCrawler/i",
				"/DomainSigmaCrawler/i",
				"/DomainStatsBot/i",
				"/Domains\ Project/i",
				"/Dotbot/i",
				"/Download\ Wonder/i",
				"/Dragonfly/i",
				"/Drip/i",
				"/ECCP/1.0/i",
				"/EMail\ Siphon/i",
				"/EMail\ Wolf/i",
				"/EasyDL/i",
				"/Ebingbong/i",
				"/Ecxi/i",
				"/EirGrabber/i",
				"/EroCrawler/i",
				"/Evil/i",
				"/Exabot/i",
				"/Express\ WebPictures/i",
				"/ExtLinksBot/i",
				"/Extractor/i",
				"/ExtractorPro/i",
				"/Extreme\ Picture\ Finder/i",
				"/EyeNetIE/i",
				"/Ezooms/i",
				"/FDM/i",
				"/FHscan/i",
				"/FemtosearchBot/i",
				"/Fimap/i",
				"/Firefox/7.0/i",
				"/FlashGet/i",
				"/Flunky/i",
				"/Foobot/i",
				"/Freeuploader/i",
				"/FrontPage/i",
				"/Fuzz/i",
				"/FyberSpider/i",
				"/Fyrebot/i",
				"/G-i-g-a-b-o-t/i",
				"/GPTBot/i",
				"/GT::WWW/i",
				"/GalaxyBot/i",
				"/Genieo/i",
				"/GermCrawler/i",
				"/GetRight/i",
				"/GetWeb/i",
				"/Getintent/i",
				"/Gigabot/i",
				"/Go!Zilla/i",
				"/Go-Ahead-Got-It/i",
				"/GoZilla/i",
				"/Gotit/i",
				"/GrabNet/i",
				"/Grabber/i",
				"/Grafula/i",
				"/GrapeFX/i",
				"/GrapeshotCrawler/i",
				"/GridBot/i",
				"/HEADMasterSEO/i",
				"/HMView/i",
				"/HTMLparser/i",
				"/HTTP::Lite/i",
				"/HTTrack/i",
				"/Haansoft/i",
				"/HaosouSpider/i",
				"/Harvest/i",
				"/Havij/i",
				"/Heritrix/i",
				"/Hloader/i",
				"/HonoluluBot/i",
				"/Humanlinks/i",
				"/HybridBot/i",
				"/IDBTE4M/i",
				"/IDBot/i",
				"/IRLbot/i",
				"/Iblog/i",
				"/Id-search/i",
				"/IlseBot/i",
				"/Image\ Fetch/i",
				"/Image\ Sucker/i",
				"/IndeedBot/i",
				"/Indy\ Library/i",
				"/InfoNaviRobot/i",
				"/InfoTekies/i",
				"/Intelliseek/i",
				"/InterGET/i",
				"/InternetSeer/i",
				"/Internet\ Ninja/i",
				"/Iria/i",
				"/Iskanie/i",
				"/IstellaBot/i",
				"/JOC\ Web\ Spider/i",
				"/JamesBOT/i",
				"/Jbrofuzz/i",
				"/JennyBot/i",
				"/JetCar/i",
				"/Jetty/i",
				"/JikeSpider/i",
				"/Joomla/i",
				"/Jorgee/i",
				"/JustView/i",
				"/Jyxobot/i",
				"/Kenjin\ Spider/i",
				"/Keybot\ Translation-Search-Machine/i",
				"/Keyword\ Density/i",
				"/Kinza/i",
				"/Kozmosbot/i",
				"/LNSpiderguy/i",
				"/LWP::Simple/i",
				"/Lanshanbot/i",
				"/Larbin/i",
				"/Leap/i",
				"/LeechFTP/i",
				"/LeechGet/i",
				"/LexiBot/i",
				"/Lftp/i",
				"/LibWeb/i",
				"/Libwhisker/i",
				"/LieBaoFast/i",
				"/Lightspeedsystems/i",
				"/Likse/i",
				"/LinkScan/i",
				"/LinkWalker/i",
				"/Linkbot/i",
				"/LinkextractorPro/i",
				"/LinkpadBot/i",
				"/LinksManager/i",
				"/LinqiaMetadataDownloaderBot/i",
				"/LinqiaRSSBot/i",
				"/LinqiaScrapeBot/i",
				"/Lipperhey/i",
				"/Lipperhey\ Spider/i",
				"/Litemage_walker/i",
				"/Lmspider/i",
				"/Ltx71/i",
				"/MFC_Tear_Sample/i",
				"/MIDown\ tool/i",
				"/MIIxpc/i",
				"/MJ12bot/i",
				"/MQQBrowser/i",
				"/MSFrontPage/i",
				"/MSIECrawler/i",
				"/MTRobot/i",
				"/Mag-Net/i",
				"/Magnet/i",
				"/Mail.RU_Bot/i",
				"/Majestic-SEO/i",
				"/Majestic12/i",
				"/Majestic\ SEO/i",
				"/MarkMonitor/i",
				"/MarkWatch/i",
				"/Mass\ Downloader/i",
				"/Masscan/i",
				"/Mata\ Hari/i",
				"/MauiBot/i",
				"/Mb2345Browser/i",
				"/MeanPath\ Bot/i",
				"/Meanpathbot/i",
				"/Mediatoolkitbot/i",
				"/MegaIndex.ru/i",
				"/Metauri/i",
				"/MicroMessenger/i",
				"/Microsoft\ Data\ Access/i",
				"/Microsoft\ URL\ Control/i",
				"/Minefield/i",
				"/Mister\ PiX/i",
				"/Moblie\ Safari/i",
				"/Mojeek/i",
				"/Mojolicious/i",
				"/MolokaiBot/i",
				"/Morfeus\ Fucking\ Scanner/i",
				"/Mozlila/i",
				"/Mr.4x3/i",
				"/Msrabot/i",
				"/Musobot/i",
				"/NICErsPRO/i",
				"/NPbot/i",
				"/Name\ Intelligence/i",
				"/Nameprotect/i",
				"/Navroad/i",
				"/NearSite/i",
				"/Needle/i",
				"/Nessus/i",
				"/NetAnts/i",
				"/NetLyzer/i",
				"/NetMechanic/i",
				"/NetSpider/i",
				"/NetZIP/i",
				"/Net\ Vampire/i",
				"/Netcraft/i",
				"/Nettrack/i",
				"/Netvibes/i",
				"/NextGenSearchBot/i",
				"/Nibbler/i",
				"/Niki-bot/i",
				"/Nikto/i",
				"/NimbleCrawler/i",
				"/Nimbostratus/i",
				"/Ninja/i",
				"/Nmap/i",
				"/Nuclei/i",
				"/Nutch/i",
				"/Octopus/i",
				"/Offline\ Explorer/i",
				"/Offline\ Navigator/i",
				"/OnCrawl/i",
				"/OpenLinkProfiler/i",
				"/OpenVAS/i",
				"/Openfind/i",
				"/Openvas/i",
				"/OrangeBot/i",
				"/OrangeSpider/i",
				"/OutclicksBot/i",
				"/OutfoxBot/i",
				"/PECL::HTTP/i",
				"/PHPCrawl/i",
				"/POE-Component-Client-HTTP/i",
				"/PageAnalyzer/i",
				"/PageGrabber/i",
				"/PageScorer/i",
				"/PageThing.com/i",
				"/Page\ Analyzer/i",
				"/Pandalytics/i",
				"/Panscient/i",
				"/Papa\ Foto/i",
				"/Pavuk/i",
				"/PeoplePal/i",
				"/Petalbot/i",
				"/Pi-Monster/i",
				"/Picscout/i",
				"/Picsearch/i",
				"/PictureFinder/i",
				"/Piepmatz/i",
				"/Pimonster/i",
				"/Pixray/i",
				"/PleaseCrawl/i",
				"/Pockey/i",
				"/ProPowerBot/i",
				"/ProWebWalker/i",
				"/Probethenet/i",
				"/Proximic/i",
				"/Psbot/i",
				"/Pu_iN/i",
				"/Pump/i",
				"/PxBroker/i",
				"/PyCurl/i",
				"/QueryN\ Metasearch/i",
				"/Quick-Crawler/i",
				"/RSSingBot/i",
				"/Rainbot/i",
				"/RankActive/i",
				"/RankActiveLinkBot/i",
				"/RankFlex/i",
				"/RankingBot/i",
				"/RankingBot2/i",
				"/Rankivabot/i",
				"/RankurBot/i",
				"/Re-re/i",
				"/ReGet/i",
				"/RealDownload/i",
				"/Reaper/i",
				"/RebelMouse/i",
				"/Recorder/i",
				"/RedesScrapy/i",
				"/RepoMonkey/i",
				"/Ripper/i",
				"/RocketCrawler/i",
				"/Rogerbot/i",
				"/SBIder/i",
				"/SEOkicks/i",
				"/SEOkicks-Robot/i",
				"/SEOlyticsCrawler/i",
				"/SEOprofiler/i",
				"/SEOstats/i",
				"/SISTRIX/i",
				"/SMTBot/i",
				"/SalesIntelligent/i",
				"/ScanAlert/i",
				"/Scanbot/i",
				"/ScoutJet/i",
				"/Scrapy/i",
				"/Screaming/i",
				"/ScreenerBot/i",
				"/ScrepyBot/i",
				"/Searchestate/i",
				"/SearchmetricsBot/i",
				"/Seekport/i",
				"/SeekportBot/i",
				"/SemanticJuice/i",
				"/Semrush/i",
				"/SemrushBot/i",
				"/SentiBot/i",
				"/SenutoBot/i",
				"/SeoSiteCheckup/i",
				"/SeobilityBot/i",
				"/Seomoz/i",
				"/Shodan/i",
				"/Siphon/i",
				"/SiteCheckerBotCrawler/i",
				"/SiteExplorer/i",
				"/SiteLockSpider/i",
				"/SiteSnagger/i",
				"/SiteSucker/i",
				"/Site\ Sucker/i",
				"/Sitebeam/i",
				"/Siteimprove/i",
				"/Sitevigil/i",
				"/SlySearch/i",
				"/SmartDownload/i",
				"/Snake/i",
				"/Snapbot/i",
				"/Snoopy/i",
				"/SocialRankIOBot/i",
				"/Sociscraper/i",
				"/Sogou\ web\ spider/i",
				"/Sosospider/i",
				"/Sottopop/i",
				"/SpaceBison/i",
				"/Spammen/i",
				"/SpankBot/i",
				"/Spanner/i",
				"/Spbot/i",
				"/Spinn3r/i",
				"/SputnikBot/i",
				"/Sqlmap/i",
				"/Sqlworm/i",
				"/Sqworm/i",
				"/Steeler/i",
				"/Stripper/i",
				"/Sucker/i",
				"/Sucuri/i",
				"/SuperBot/i",
				"/SuperHTTP/i",
				"/Surfbot/i",
				"/SurveyBot/i",
				"/Suzuran/i",
				"/Swiftbot/i",
				"/Szukacz/i",
				"/T0PHackTeam/i",
				"/T8Abot/i",
				"/Teleport/i",
				"/TeleportPro/i",
				"/Telesoft/i",
				"/Telesphoreo/i",
				"/Telesphorep/i",
				"/TheNomad/i",
				"/The\ Intraformant/i",
				"/Thumbor/i",
				"/TightTwatBot/i",
				"/TinyTestBot/i",
				"/Titan/i",
				"/Toata/i",
				"/Toweyabot/i",
				"/Tracemyfile/i",
				"/Trendiction/i",
				"/Trendictionbot/i",
				"/True_Robot/i",
				"/Turingos/i",
				"/Turnitin/i",
				"/TurnitinBot/i",
				"/TwengaBot/i",
				"/Twice/i",
				"/Typhoeus/i",
				"/URLy.Warning/i",
				"/URLy\ Warning/i",
				"/UnisterBot/i",
				"/Upflow/i",
				"/V-BOT/i",
				"/VB\ Project/i",
				"/VCI/i",
				"/Vacuum/i",
				"/Vagabondo/i",
				"/VelenPublicWebCrawler/i",
				"/VeriCiteCrawler/i",
				"/VidibleScraper/i",
				"/Virusdie/i",
				"/VoidEYE/i",
				"/Voil/i",
				"/Voltron/i",
				"/WASALive-Bot/i",
				"/WBSearchBot/i",
				"/WEBDAV/i",
				"/WISENutbot/i",
				"/WPScan/i",
				"/WWW-Collector-E/i",
				"/WWW-Mechanize/i",
				"/WWW::Mechanize/i",
				"/WWWOFFLE/i",
				"/Wallpapers/i",
				"/Wallpapers/3.0/i",
				"/WallpapersHD/i",
				"/WeSEE/i",
				"/WebAuto/i",
				"/WebBandit/i",
				"/WebCollage/i",
				"/WebCopier/i",
				"/WebEnhancer/i",
				"/WebFetch/i",
				"/WebFuck/i",
				"/WebGo\ IS/i",
				"/WebImageCollector/i",
				"/WebLeacher/i",
				"/WebPix/i",
				"/WebReaper/i",
				"/WebSauger/i",
				"/WebStripper/i",
				"/WebSucker/i",
				"/WebWhacker/i",
				"/WebZIP/i",
				"/Web\ Auto/i",
				"/Web\ Collage/i",
				"/Web\ Enhancer/i",
				"/Web\ Fetch/i",
				"/Web\ Fuck/i",
				"/Web\ Pix/i",
				"/Web\ Sauger/i",
				"/Web\ Sucker/i",
				"/Webalta/i",
				"/WebmasterWorldForumBot/i",
				"/Webshag/i",
				"/WebsiteExtractor/i",
				"/WebsiteQuester/i",
				"/Website\ Quester/i",
				"/Webster/i",
				"/Whack/i",
				"/Whacker/i",
				"/Whatweb/i",
				"/Who.is\ Bot/i",
				"/Widow/i",
				"/WinHTTrack/i",
				"/WiseGuys\ Robot/i",
				"/Wonderbot/i",
				"/Woobot/i",
				"/Wotbox/i",
				"/Wprecon/i",
				"/Xaldon\ WebSpider/i",
				"/Xaldon_WebSpider/i",
				"/Xenu/i",
				"/YoudaoBot/i",
				"/Zade/i",
				"/Zauba/i",
				"/Zermelo/i",
				"/Zeus/i",
				"/Zitebot/i",
				"/ZmEu/i",
				"/ZoomBot/i",
				"/ZoominfoBot/i",
				"/ZumBot/i",
				"/ZyBorg/i",
				"/adscanner/i",
				"/archive.org_bot/i",
				"/arquivo-web-crawler/i",
				"/arquivo.pt/i",
				"/autoemailspider/i",
				"/backlink-check/i",
				"/cah.io.community/i",
				"/check1.exe/i",
				"/clark-crawler/i",
				"/coccocbot/i",
				"/cognitiveseo/i",
				"/com.plumanalytics/i",
				"/crawl.sogou.com/i",
				"/crawler.feedback/i",
				"/crawler4j/i",
				"/dataforseo.com/i",
				"/dataforseobot/i",
				"/demandbase-bot/i",
				"/domainsproject.org/i",
				"/eCatch/i",
				"/evc-batch/i",
				"/facebookscraper/i",
				"/gopher/i",
				"/heritrix/i",
				"/instabid/i",
				"/internetVista\ monitor/i",
				"/ips-agent/i",
				"/isitwp.com/i",
				"/iubenda-radar/i",
				"/linkdexbot/i",
				"/lwp-request/i",
				"/lwp-trivial/i",
				"/magpie-crawler/i",
				"/meanpathbot/i",
				"/mediawords/i",
				"/muhstik-scan/i",
				"/netEstate\ NE\ Crawler/i",
				"/oBot/i",
				"/openai/i",
				"/openai.com/i",
				"/page\ scorer/i",
				"/pcBrowser/i",
				"/plumanalytics/i",
				"/polaris\ version/i",
				"/probe-image-size/i",
				"/ripz/i",
				"/s1z.ru/i",
				"/satoristudio.net/i",
				"/scalaj-http/i",
				"/scan.lol/i",
				"/seobility/i",
				"/seocompany.store/i",
				"/seoscanners/i",
				"/seostar/i",
				"/serpstatbot/i",
				"/sexsearcher/i",
				"/sitechecker.pro/i",
				"/siteripz/i",
				"/sogouspider/i",
				"/sp_auditbot/i",
				"/spyfu/i",
				"/sysscan/i",
				"/tAkeOut/i",
				"/trendiction.com/i",
				"/trendiction.de/i",
				"/ubermetrics-technologies.com/i",
				"/voyagerx.com/i",
				"/webgains-bot/i",
				"/webmeup-crawler/i",
				"/webpros.com/i",
				"/webprosbot/i",
				"/x09Mozilla/i",
				"/x22Mozilla/i",
				"/xpymep1.exe/i",
				"/zauba.io/i",
				"/zgrab/i",
				"/python/i",
				"/python-requests/i",
				"/sogou/i",
				"/spider/i",
				"/spiderbot/i",
				"/Go-http-client/i",
				"/Hello/i",
				"/curl/i",
				"/libwww/i",
				"/Mozilla/5.0 zgrab/0.x/i",
				"/Scripting/i",
				"/Scrapy/i",
				"/Scrapy/VERSION/i",
				"/nmap/i",
				"/CensysInspect/i",
				"/masscan/i",
				"/scan/i",
				"/kali/i",
			];
			$userAgent = strtolower($userAgent);
			foreach ($blockedUserAgentList as $pattern) {
				if (preg_match($pattern, $userAgent)) {
					return true;
				}
			}
			return false;
		}
		*/
		
		
	  	private function badUserAgent($userAgent):bool
		{
			$userAgent= strtolower($userAgent);
			$blockedUserAgentList=[
				"01h4x.com",
				"360Spider",
				"404checker",
				"404enemy",
				"80legs",
				"ADmantX",
				"AIBOT",
				"ALittle\ Client",
				"ASPSeek",
				"Abonti",
				"Aboundex",
				"Aboundexbot",
				"Acunetix",
				"AdsTxtCrawlerTP",
				"AfD-Verbotsverfahren",
				"AhrefsBot",
				"AiHitBot",
				"Aipbot",
				"Alexibot",
				"AllSubmitter",
				"Alligator",
				"AlphaBot",
				"Anarchie",
				"Anarchy",
				"Anarchy99",
				"Ankit",
				"Anthill",
				"Apexoo",
				"Aspiegel",
				"Asterias",
				"Atomseobot",
				"Attach",
				"AwarioRssBot",
				"AwarioSmartBot",
				"BBBike",
				"BDCbot",
				"BDFetch",
				"BLEXBot",
				"BackDoorBot",
				"BackStreet",
				"BackWeb",
				"Backlink-Ceck",
				"BacklinkCrawler",
				"Badass",
				"Bandit",
				"Barkrowler",
				"BatchFTP",
				"Battleztar\ Bazinga",
				"BetaBot",
				"Bigfoot",
				"Bitacle",
				"BlackWidow",
				"Black\ Hole",
				"Blackboard",
				"Blow",
				"BlowFish",
				"Boardreader",
				"Bolt",
				"BotALot",
				"Brandprotect",
				"Brandwatch",
				"Buck",
				"Buddy",
				"BuiltBotTough",
				"BuiltWith",
				"Bullseye",
				"BunnySlippers",
				"BuzzSumo",
				"Bytespider",
				"CATExplorador",
				"CCBot",
				"CODE87",
				"CSHttp",
				"Calculon",
				"CazoodleBot",
				"Cegbfeieh",
				"CensysInspect",
				"CheTeam",
				"CheeseBot",
				"CherryPicker",
				"ChinaClaw",
				"Chlooe",
				"Citoid",
				"Claritybot",
				"Cliqzbot",
				"Cloud\ mapping",
				"Cocolyzebot",
				"Cogentbot",
				"Collector",
				"Copier",
				"CopyRightCheck",
				"Copyscape",
				"Cosmos",
				"Craftbot",
				"Crawling\ at\ Home\ Project",
				"CrazyWebCrawler",
				"Crescent",
				"CrunchBot",
				"Curious",
				"Custo",
				"CyotekWebCopy",
				"DBLBot",
				"DIIbot",
				"DSearch",
				"DTS\ Agent",
				"DataCha0s",
				"DatabaseDriverMysqli",
				"Demon",
				"Deusu",
				"Devil",
				"Digincore",
				"DigitalPebble",
				"Dirbuster",
				"Disco",
				"Discobot",
				"Discoverybot",
				"Dispatch",
				"DittoSpyder",
				"DnBCrawler-Analytics",
				"DnyzBot",
				"DomCopBot",
				"DomainAppender",
				"DomainCrawler",
				"DomainSigmaCrawler",
				"DomainStatsBot",
				"Domains\ Project",
				"Dotbot",
				"Download\ Wonder",
				"Dragonfly",
				"Drip",
				"ECCP/1.0",
				"EMail\ Siphon",
				"EMail\ Wolf",
				"EasyDL",
				"Ebingbong",
				"Ecxi",
				"EirGrabber",
				"EroCrawler",
				"Evil",
				"Exabot",
				"Express\ WebPictures",
				"ExtLinksBot",
				"Extractor",
				"ExtractorPro",
				"Extreme\ Picture\ Finder",
				"EyeNetIE",
				"Ezooms",
				"FDM",
				"FHscan",
				"FemtosearchBot",
				"Fimap",
				"Firefox/7.0",
				"FlashGet",
				"Flunky",
				"Foobot",
				"Freeuploader",
				"FrontPage",
				"Fuzz",
				"FyberSpider",
				"Fyrebot",
				"G-i-g-a-b-o-t",
				"GPTBot",
				"GT::WWW",
				"GalaxyBot",
				"Genieo",
				"GermCrawler",
				"GetRight",
				"GetWeb",
				"Getintent",
				"Gigabot",
				"Go!Zilla",
				"Go-Ahead-Got-It",
				"GoZilla",
				"Gotit",
				"GrabNet",
				"Grabber",
				"Grafula",
				"GrapeFX",
				"GrapeshotCrawler",
				"GridBot",
				"HEADMasterSEO",
				"HMView",
				"HTMLparser",
				"HTTP::Lite",
				"HTTrack",
				"Haansoft",
				"HaosouSpider",
				"Harvest",
				"Havij",
				"Heritrix",
				"Hloader",
				"HonoluluBot",
				"Humanlinks",
				"HybridBot",
				"IDBTE4M",
				"IDBot",
				"IRLbot",
				"Iblog",
				"Id-search",
				"IlseBot",
				"Image\ Fetch",
				"Image\ Sucker",
				"IndeedBot",
				"Indy\ Library",
				"InfoNaviRobot",
				"InfoTekies",
				"Intelliseek",
				"InterGET",
				"InternetSeer",
				"Internet\ Ninja",
				"Iria",
				"Iskanie",
				"IstellaBot",
				"JOC\ Web\ Spider",
				"JamesBOT",
				"Jbrofuzz",
				"JennyBot",
				"JetCar",
				"Jetty",
				"JikeSpider",
				"Joomla",
				"Jorgee",
				"JustView",
				"Jyxobot",
				"Kenjin\ Spider",
				"Keybot\ Translation-Search-Machine",
				"Keyword\ Density",
				"Kinza",
				"Kozmosbot",
				"LNSpiderguy",
				"LWP::Simple",
				"Lanshanbot",
				"Larbin",
				"Leap",
				"LeechFTP",
				"LeechGet",
				"LexiBot",
				"Lftp",
				"LibWeb",
				"Libwhisker",
				"LieBaoFast",
				"Lightspeedsystems",
				"Likse",
				"LinkScan",
				"LinkWalker",
				"Linkbot",
				"LinkextractorPro",
				"LinkpadBot",
				"LinksManager",
				"LinqiaMetadataDownloaderBot",
				"LinqiaRSSBot",
				"LinqiaScrapeBot",
				"Lipperhey",
				"Lipperhey\ Spider",
				"Litemage_walker",
				"Lmspider",
				"Ltx71",
				"MFC_Tear_Sample",
				"MIDown\ tool",
				"MIIxpc",
				"MJ12bot",
				"MQQBrowser",
				"MSFrontPage",
				"MSIECrawler",
				"MTRobot",
				"Mag-Net",
				"Magnet",
				"Mail.RU_Bot",
				"Majestic-SEO",
				"Majestic12",
				"Majestic\ SEO",
				"MarkMonitor",
				"MarkWatch",
				"Mass\ Downloader",
				"Masscan",
				"Mata\ Hari",
				"MauiBot",
				"Mb2345Browser",
				"MeanPath\ Bot",
				"Meanpathbot",
				"Mediatoolkitbot",
				"MegaIndex.ru",
				"Metauri",
				"MicroMessenger",
				"Microsoft\ Data\ Access",
				"Microsoft\ URL\ Control",
				"Minefield",
				"Mister\ PiX",
				"Moblie\ Safari",
				"Mojeek",
				"Mojolicious",
				"MolokaiBot",
				"Morfeus\ Fucking\ Scanner",
				"Mozlila",
				"Mr.4x3",
				"Msrabot",
				"Musobot",
				"NICErsPRO",
				"NPbot",
				"Name\ Intelligence",
				"Nameprotect",
				"Navroad",
				"NearSite",
				"Needle",
				"Nessus",
				"NetAnts",
				"NetLyzer",
				"NetMechanic",
				"NetSpider",
				"NetZIP",
				"Net\ Vampire",
				"Netcraft",
				"Nettrack",
				"Netvibes",
				"NextGenSearchBot",
				"Nibbler",
				"Niki-bot",
				"Nikto",
				"NimbleCrawler",
				"Nimbostratus",
				"Ninja",
				"Nmap",
				"Nuclei",
				"Nutch",
				"Octopus",
				"Offline\ Explorer",
				"Offline\ Navigator",
				"OnCrawl",
				"OpenLinkProfiler",
				"OpenVAS",
				"Openfind",
				"Openvas",
				"OrangeBot",
				"OrangeSpider",
				"OutclicksBot",
				"OutfoxBot",
				"PECL::HTTP",
				"PHPCrawl",
				"POE-Component-Client-HTTP",
				"PageAnalyzer",
				"PageGrabber",
				"PageScorer",
				"PageThing.com",
				"Page\ Analyzer",
				"Pandalytics",
				"Panscient",
				"Papa\ Foto",
				"Pavuk",
				"PeoplePal",
				"Petalbot",
				"Pi-Monster",
				"Picscout",
				"Picsearch",
				"PictureFinder",
				"Piepmatz",
				"Pimonster",
				"Pixray",
				"PleaseCrawl",
				"Pockey",
				"ProPowerBot",
				"ProWebWalker",
				"Probethenet",
				"Proximic",
				"Psbot",
				"Pu_iN",
				"Pump",
				"PxBroker",
				"PyCurl",
				"QueryN\ Metasearch",
				"Quick-Crawler",
				"RSSingBot",
				"Rainbot",
				"RankActive",
				"RankActiveLinkBot",
				"RankFlex",
				"RankingBot",
				"RankingBot2",
				"Rankivabot",
				"RankurBot",
				"Re-re",
				"ReGet",
				"RealDownload",
				"Reaper",
				"RebelMouse",
				"Recorder",
				"RedesScrapy",
				"RepoMonkey",
				"Ripper",
				"RocketCrawler",
				"Rogerbot",
				"SBIder",
				"SEOkicks",
				"SEOkicks-Robot",
				"SEOlyticsCrawler",
				"SEOprofiler",
				"SEOstats",
				"SISTRIX",
				"SMTBot",
				"SalesIntelligent",
				"ScanAlert",
				"Scanbot",
				"ScoutJet",
				"Scrapy",
				"Screaming",
				"ScreenerBot",
				"ScrepyBot",
				"Searchestate",
				"SearchmetricsBot",
				"Seekport",
				"SeekportBot",
				"SemanticJuice",
				"Semrush",
				"SemrushBot",
				"SentiBot",
				"SenutoBot",
				"SeoSiteCheckup",
				"SeobilityBot",
				"Seomoz",
				"Shodan",
				"Siphon",
				"SiteCheckerBotCrawler",
				"SiteExplorer",
				"SiteLockSpider",
				"SiteSnagger",
				"SiteSucker",
				"Site\ Sucker",
				"Sitebeam",
				"Siteimprove",
				"Sitevigil",
				"SlySearch",
				"SmartDownload",
				"Snake",
				"Snapbot",
				"Snoopy",
				"SocialRankIOBot",
				"Sociscraper",
				"Sogou\ web\ spider",
				"Sosospider",
				"Sottopop",
				"SpaceBison",
				"Spammen",
				"SpankBot",
				"Spanner",
				"Spbot",
				"Spinn3r",
				"SputnikBot",
				"Sqlmap",
				"Sqlworm",
				"Sqworm",
				"Steeler",
				"Stripper",
				"Sucker",
				"Sucuri",
				"SuperBot",
				"SuperHTTP",
				"Surfbot",
				"SurveyBot",
				"Suzuran",
				"Swiftbot",
				"Szukacz",
				"T0PHackTeam",
				"T8Abot",
				"Teleport",
				"TeleportPro",
				"Telesoft",
				"Telesphoreo",
				"Telesphorep",
				"TheNomad",
				"The\ Intraformant",
				"Thumbor",
				"TightTwatBot",
				"TinyTestBot",
				"Titan",
				"Toata",
				"Toweyabot",
				"Tracemyfile",
				"Trendiction",
				"Trendictionbot",
				"True_Robot",
				"Turingos",
				"Turnitin",
				"TurnitinBot",
				"TwengaBot",
				"Twice",
				"Typhoeus",
				"URLy.Warning",
				"URLy\ Warning",
				"UnisterBot",
				"Upflow",
				"V-BOT",
				"VB\ Project",
				"VCI",
				"Vacuum",
				"Vagabondo",
				"VelenPublicWebCrawler",
				"VeriCiteCrawler",
				"VidibleScraper",
				"Virusdie",
				"VoidEYE",
				"Voil",
				"Voltron",
				"WASALive-Bot",
				"WBSearchBot",
				"WEBDAV",
				"WISENutbot",
				"WPScan",
				"WWW-Collector-E",
				"WWW-Mechanize",
				"WWW::Mechanize",
				"WWWOFFLE",
				"Wallpapers",
				"Wallpapers/3.0",
				"WallpapersHD",
				"WeSEE",
				"WebAuto",
				"WebBandit",
				"WebCollage",
				"WebCopier",
				"WebEnhancer",
				"WebFetch",
				"WebFuck",
				"WebGo\ IS",
				"WebImageCollector",
				"WebLeacher",
				"WebPix",
				"WebReaper",
				"WebSauger",
				"WebStripper",
				"WebSucker",
				"WebWhacker",
				"WebZIP",
				"Web\ Auto",
				"Web\ Collage",
				"Web\ Enhancer",
				"Web\ Fetch",
				"Web\ Fuck",
				"Web\ Pix",
				"Web\ Sauger",
				"Web\ Sucker",
				"Webalta",
				"WebmasterWorldForumBot",
				"Webshag",
				"WebsiteExtractor",
				"WebsiteQuester",
				"Website\ Quester",
				"Webster",
				"Whack",
				"Whacker",
				"Whatweb",
				"Who.is\ Bot",
				"Widow",
				"WinHTTrack",
				"WiseGuys\ Robot",
				"Wonderbot",
				"Woobot",
				"Wotbox",
				"Wprecon",
				"Xaldon\ WebSpider",
				"Xaldon_WebSpider",
				"Xenu",
				"YoudaoBot",
				"Zade",
				"Zauba",
				"Zermelo",
				"Zeus",
				"Zitebot",
				"ZmEu",
				"ZoomBot",
				"ZoominfoBot",
				"ZumBot",
				"ZyBorg",
				"adscanner",
				"archive.org_bot",
				"arquivo-web-crawler",
				"arquivo.pt",
				"autoemailspider",
				"backlink-check",
				"cah.io.community",
				"check1.exe",
				"clark-crawler",
				"coccocbot",
				"cognitiveseo",
				"com.plumanalytics",
				"crawl.sogou.com",
				"crawler.feedback",
				"crawler4j",
				"dataforseo.com",
				"dataforseobot",
				"demandbase-bot",
				"domainsproject.org",
				"eCatch",
				"evc-batch",
				"facebookscraper",
				"gopher",
				"heritrix",
				"instabid",
				"internetVista\ monitor",
				"ips-agent",
				"isitwp.com",
				"iubenda-radar",
				"linkdexbot",
				"lwp-request",
				"lwp-trivial",
				"magpie-crawler",
				"meanpathbot",
				"mediawords",
				"muhstik-scan",
				"netEstate\ NE\ Crawler",
				"oBot",
				"openai",
				"openai.com",
				"page\ scorer",
				"pcBrowser",
				"plumanalytics",
				"polaris\ version",
				"probe-image-size",
				"ripz",
				"s1z.ru",
				"satoristudio.net",
				"scalaj-http",
				"scan.lol",
				"seobility",
				"seocompany.store",
				"seoscanners",
				"seostar",
				"serpstatbot",
				"sexsearcher",
				"sitechecker.pro",
				"siteripz",
				"sogouspider",
				"sp_auditbot",
				"spyfu",
				"sysscan",
				"tAkeOut",
				"trendiction.com",
				"trendiction.de",
				"ubermetrics-technologies.com",
				"voyagerx.com",
				"webgains-bot",
				"webmeup-crawler",
				"webpros.com",
				"webprosbot",
				"x09Mozilla",
				"x22Mozilla",
				"xpymep1.exe",
				"zauba.io",
				"zgrab",
				"python",
				"python-requests",
				"sogou",
				"spider",
				"spiderbot",
				"Go-http-client",
				"Hello",
				"curl",
				"libwww",
				"Mozilla/5.0 zgrab/0.x",
				"Scripting",
				"Scrapy",
				"Scrapy/VERSION",
				"nmap",
				"CensysInspect",
				"masscan",
				"scan",
				"kali",
				
			];
			foreach ($blockedUserAgentList as $blockedUserAgent) {
				if (str_contains($userAgent, strtolower($blockedUserAgent))) {
					return true;
				}
			}
			return false;
		}

		
	}
