# see https://symfony.com/doc/current/reference/configuration/framework.html

framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_cache: true
    cache:
        #app: cache.adapter.apcu
        #system: cache.adapter.system
        #directory: '%kernel.cache_dir%/system'
        #default_redis_provider: 'redis://localhost:6379'
        #default_memcached_provider: 'memcached://localhost:11211'
        #pools:
            #my_redis_pool:
                #adapter: cache.adapter.redis
                #provider: '%default_redis_provider%'
                #default_lifetime: 0 # no cache expiration
            #my_memcached_pool:
                #adapter: cache.adapter.memcached
                #provider: '%default_memcached_provider%'
                #default_lifetime: 0 # no cache expiration
    http_method_override: false
    handle_all_throwables: true
    fragments:
        #path: /_fragment # required for the hinclude feature
        hinclude_default_template: dashboard/_partials/_utils/_hinclude.html.twig
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@dev:
    #_errors:
        #resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        #prefix:   /_error